// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var call,
    __slice = [].slice;

  call = function() {
    var args, fn, frame;
    frame = arguments[0], fn = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    fn.apply(null, [frame.__node].concat(__slice.call(args)));
    return frame;
  };

  module.exports = call;

}).call(this);
