// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var partial;

  partial = function(frame, name) {
    var _base, _ref;
    if ((_ref = (_base = frame.__parent).partials) == null) {
      _base.partials = {};
    }
    frame.__parent.partials[name] = frame.__node.html();
    return frame;
  };

  partial.raw = /^[^"'].*$/;

  module.exports = {
    partial: partial
  };

}).call(this);
