// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var assoc, get, isRef, props, ref, _ref, _ref1,
    __slice = [].slice;

  _ref = require('../../core/reference'), ref = _ref.ref, isRef = _ref.isRef;

  _ref1 = require('../../protocol/map'), get = _ref1.get, assoc = _ref1.assoc;

  props = function() {
    var arg, args, frame, refs, _i, _len;
    frame = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    refs = (get(frame, 'refs')) || {};
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      arg = args[_i];
      if (!isRef(refs[arg])) {
        refs[arg] = ref();
      }
    }
    frame['refs'] = refs;
    return frame;
  };

  props.raw = /^[^"'].*$/;

  module.exports = props;

}).call(this);
