// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var assertFn, isFn;

  isFn = function(value) {
    return typeof value === 'function';
  };

  assertFn = function(value, message) {
    if (message == null) {
      message = 'Invalid function';
    }
    if (!(isFn(value))) {
      throw new Error(message);
    }
    return value;
  };

  module.exports = {
    isFn: isFn,
    assertFn: assertFn
  };

}).call(this);
