// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var assertNum, isNum;

  isNum = function(value) {
    return !(isNaN(value)) && typeof value === 'number';
  };

  assertNum = function(value, message) {
    if (message == null) {
      message = 'Invalid number';
    }
    if (!(isNum(value))) {
      throw new Error(message);
    }
    return value;
  };

  module.exports = {
    isNum: isNum,
    assertNum: assertNum
  };

}).call(this);
