// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var assertObj, isArr, isObj;

  isArr = require('./array').isArr;

  isObj = function(value) {
    return (value != null) && (typeof value === 'object') && (!isArr(value));
  };

  assertObj = function(value, message) {
    if (message == null) {
      message = 'Invalid object';
    }
    if (!(isObj(value))) {
      throw new Error(message);
    }
    return value;
  };

  module.exports = {
    isObj: isObj,
    assertObj: assertObj
  };

}).call(this);
