// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var assertStr, isStr;

  isStr = function(value) {
    return typeof value === 'string';
  };

  assertStr = function(value, message) {
    if (message == null) {
      message = 'Invalid string';
    }
    if (!(isStr(value))) {
      throw new Error(message);
    }
    return value;
  };

  module.exports = {
    isStr: isStr,
    assertStr: assertStr
  };

}).call(this);
