// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var query, ref, template;

  query = require('./core/query');

  ref = require('./core/reference');

  template = require('./core/template');

  module.exports = {
    container: query.container,
    role: query.role,
    roles: query.roles,
    query: query.query,
    list: require('./core/list'),
    onEvent: query.onEvent,
    "on": query.on,
    set: ref.set,
    get: ref.get,
    notify: ref.notify,
    copy: ref.copy,
    form: require('./core/form'),
    html: require('./core/html'),
    state: require('./core/state').state,
    template: template.template,
    render: template.render,
    renderRaw: template.renderRaw,
    global: require('./core/global'),
    watch: ref.watch,
    watchRef: ref.watchRef
  };

}).call(this);
