// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var deprecatedMsgSent, importObj, nsDeprecated, use,
    __slice = [].slice;

  use = require('../core/evaluator').use;

  deprecatedMsgSent = false;

  nsDeprecated = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (deprecatedMsgSent === false) {
      console.log('`ns` is deprecated, please use `import`');
      deprecatedMsgSent = true;
    }
    return use.apply(null, args);
  };

  importObj = function() {
    var args, frame, obj;
    frame = arguments[0], obj = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    if (obj == null) {
      return frame;
    }
    frame = use(frame, obj);
    return importObj.apply(null, [frame].concat(__slice.call(args)));
  };

  module.exports = {
    control: require('./cosy/control'),
    "class": require('./cosy/class'),
    props: require('./cosy/props'),
    attach: require('./cosy/attach'),
    call: require('./cosy/call'),
    partial: require('./cosy/partial').partial,
    "import": importObj,
    ns: nsDeprecated
  };

}).call(this);
