// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var element, evaluate, get,
    __slice = [].slice;

  element = require('../protocol/element');

  get = require('../protocol/map').get;

  evaluate = require('../core/evaluator').evaluate;

  module.exports = {
    event: function() {
      var action, event, frame, node;
      frame = arguments[0], event = arguments[1], action = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      node = get(frame, '__node');
      element.listen(node, event, function(evt) {
        evt.preventDefault();
        return evaluate(action, frame);
      });
      return frame;
    }
  };

}).call(this);
