// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var assoc, evaluate, handle, handler, trigger,
    __slice = [].slice;

  assoc = require('../protocol/map').assoc;

  evaluate = require('../core/evaluator').evaluate;

  handler = function(frame, name) {
    return assoc(frame, name, {});
  };

  handle = function() {
    var action, frame, handler, signal;
    frame = arguments[0], handler = arguments[1], signal = arguments[2], action = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
    handler[signal] = function() {
      return evaluate(action, frame);
    };
    return frame;
  };

  trigger = function(frame, handler, name) {
    return handler[name]();
  };

  module.exports = {
    handler: handler,
    handle: handle,
    trigger: trigger
  };

}).call(this);
