// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var createRef, get, getOrInitRef, map, mutable, set;

  createRef = require('../../core/reference').ref;

  map = require('../../protocol/map');

  mutable = require('../../protocol/mutable');

  get = function(name) {
    var globals, ref;
    globals = mutable.get(map.get(this.frame, 'global'));
    ref = globals[name];
    if (ref != null) {
      return mutable.get(ref);
    } else {
      throw new Error("Unknown ref");
    }
  };

  getOrInitRef = function(name) {
    var globals, ref;
    globals = mutable.get(map.get(this.frame, 'global'));
    ref = globals[name];
    if (ref == null) {
      ref = createRef();
    }
    globals[name] = ref;
    mutable.set(map.get(this.frame, 'global'), globals);
    return ref;
  };

  set = function(name, value) {
    var ref;
    ref = getOrInitRef.call(this, name);
    return mutable.set(ref, value);
  };

  module.exports = {
    getOrInitRef: getOrInitRef,
    get: get,
    set: set
  };

}).call(this);
