// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var html, tag, tags, _fn, _i, _len;

  html = function(tag, attrs, content) {
    var element;
    element = $("<" + tag + " />");
    element.attr(attrs);
    element.html(content);
    return element;
  };

  tags = ["a", "abbr", "acronym", "address", "applet", "area", "b", "base", "basefont", "bdo", "big", "blockquote", "body", "br", "button", "caption", "center", "cite", "code", "col", "colgroup", "dd", "del", "dfn", "dir", "div", "dl", "dt", "em", "fieldset", "font", "form", "frame", "frameset", "h1", "h2", "h3", "h4", "h5", "h6", "head", "hr", "html", "i", "iframe", "img", "input", "ins", "isindex", "kbd", "label", "legend", "li", "link", "map", "menu", "meta", "noframes", "noscript", "object", "ol", "optgroup", "option", "p", "param", "pre", "q", "s", "samp", "script", "select", "small", "span", "strike", "strong", "style", "sub", "sup", "table", "tbody", "td", "textarea", "tfoot", "th", "thead", "title", "tr", "tt", "u", "ul", "var"];

  _fn = function(tag) {
    return exports[tag] = function(attrs, content) {
      return html(tag, attrs, content);
    };
  };
  for (_i = 0, _len = tags.length; _i < _len; _i++) {
    tag = tags[_i];
    _fn(tag);
  }

}).call(this);
