// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var List, Tree, createRef, isRef, _ref;

  List = require('./list').List;

  _ref = require('../../core/reference'), isRef = _ref.isRef, createRef = _ref.ref;

  Tree = (function() {

    function Tree(control, ref, template) {
      var childElement, list;
      this.control = control;
      list = new List(this.control, ref, template);
      childElement = this.control.role('children');
      if (childElement.length > 0) {
        ref.value.children = createRef();
        this.control.cosy.cmd(childElement, ['class', Tree, ref.value.children, list.itemTemplate]);
      }
    }

    return Tree;

  })();

  module.exports = {
    Tree: Tree
  };

}).call(this);
