// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var defProtocol, dispatch, proto, _ref;

  _ref = require('../core/protocol'), defProtocol = _ref.defProtocol, dispatch = _ref.dispatch;

  module.exports = proto = defProtocol({
    update: dispatch(function(entity, newValue) {}),
    remove: dispatch(function(entity) {}),
    name: dispatch(function(entity) {}),
    id: dispatch(function(entity) {})
  });

}).call(this);
