// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var defProtocol, dispatch, extend, protocol, _ref;

  _ref = require('../core/protocol'), defProtocol = _ref.defProtocol, dispatch = _ref.dispatch, extend = _ref.extend;

  module.exports = protocol = defProtocol({
    key: dispatch(function(mapItem) {}),
    value: dispatch(function(mapItem) {}),
    assoc: dispatch(function(map, key, value) {}),
    dissoc: dispatch(function(map, key) {}),
    get: dispatch(function(map, key) {}),
    find: dispatch(function(map, key) {})
  });

}).call(this);
