// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var defProtocol, dispatch, extend, isStr, proto, _ref;

  _ref = require('../core/protocol'), defProtocol = _ref.defProtocol, dispatch = _ref.dispatch, extend = _ref.extend;

  isStr = require('../core/native/string').isStr;

  module.exports = proto = defProtocol({
    set: dispatch(function(variable, value) {}),
    get: dispatch(function(variable) {})
  });

  extend(proto, isStr, {
    get: function(str) {
      return str;
    }
  });

}).call(this);
