// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var defProtocol, dispatch, extend, isJqueryElement, isStr, proto, _ref;

  _ref = require('../core/protocol'), defProtocol = _ref.defProtocol, dispatch = _ref.dispatch, extend = _ref.extend;

  isStr = require('../core/native/string').isStr;

  module.exports = proto = defProtocol({
    render: dispatch(function(template, context) {})
  });

  extend(proto, isStr, {
    render: function(template, context) {
      return template;
    }
  });

  isJqueryElement = function(value) {
    return (value != null) && (value.jquery != null);
  };

  extend(proto, isJqueryElement, {
    render: function(template, context) {
      return template;
    }
  });

}).call(this);
