// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var evaluator, hashMap, reader, up,
    __hasProp = {}.hasOwnProperty;

  reader = require('./core/reader');

  evaluator = require('./core/evaluator');

  hashMap = require('./core/hashMap').hashMap;

  up = function(startNode, imports) {
    var ast, attributes, frame, name, obj, selector;
    frame = evaluator.use(evaluator.frame(), imports);
    attributes = [];
    for (name in imports) {
      if (!__hasProp.call(imports, name)) continue;
      obj = imports[name];
      attributes.push("[data-cosy-" + name + "]");
    }
    selector = attributes.join(',');
    ast = reader.read(startNode, selector);
    return evaluator.apply(ast, frame);
  };

  module.exports = {
    up: up,
    isAwesome: true,
    snuggle: require('./snuggle')
  };

}).call(this);
